<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */


 
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<?php if($block -> isLoggedIn()): ?>
    <li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
    </li>
<?php else: ?>
    <li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
        <a 
            <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml(__('Inloggen')) ?>
        </a>
    </li>
<?php endif; ?>



