<?php
$_item = $block->getProduct();
?>

<div class="warehouse-content">
    <div class="product-attribute">
        <div class="product-attribute-item">
            <?= $escaper->escapeHtml('10 pieces in Warehouse Varpo') ?> <span> <?= $escaper->escapeHtml($_item->getData('warehouse_name')) ?></span>
        </div>
        <div class="product-attribute-item">
            <?= $escaper->escapeHtml('10 pieces in Warehouse Varpo') ?> <span> <?= $escaper->escapeHtml($_item->getData('warehouse_name')) ?></span>
        </div>
        <div class="product-attribute-item">
            <?= $escaper->escapeHtml('10 pieces in Warehouse Varpo') ?> <span> <?= $escaper->escapeHtml($_item->getData('warehouse_name')) ?></span>
        </div>
    </div>
</div>